version: '3.7'

services:
  postgresql:
    image: postgres:alpine
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
    networks: 
      - postgresql_network
    volumes: 
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  postgresql_network:
    external: true
    name: net_app
    driver: overlay
    attachable: true