version: '3.7'

services:
    example56:
      image: youngmartin45/nginx-phpfpm-ext:7.3
      volumes:
        - .:/www
      ports:
        - "8095:80"
      networks: 
        - php_network

networks:
  php_network:
      external: true
      name: net_app
      driver: overlay
      attachable: true