version: "3.7"

services:
    traefik:
        image: traefik:v2.1
        container_name: "traefik"
        hostname: "traefik"
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik.yml:/traefik.yml:ro"
            - "./users_credentials:/users_credentials:ro"
            - "./acme.json:/acme.json"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
