version: '3.7'

services:
  nodeapp:
    image: node_app:1.0.0
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7010:8080
    networks:
      - node_network
    command: node index.js

networks:
  node_network:
    external: true
    name: net_app