version: '3.7'

services:
     web:
       image: nginx:alpine
       ports:
           - "8080:80"
       volumes:
           - ./apps:/public_html
           - ./nginx:/etc/nginx/conf.d
        #    - /etc/localtime:/etc/localtime
       networks:
           - nginxphp

     php:
       image: php:7.0-fpm-alpine
       volumes:
           - ./apps:/public_html
       expose:
           - 9000
       networks:
           - nginxphp

networks:
     nginxphp: