version: '3.7'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 7002:27017
    networks: 
      - mongo_network
    volumes:
      # - mongodb_data:/data/db
      - ./mongo-data:/data/db

volumes:
    mongodb_data:

networks:
  mongo_network:
    external: true
    name: net_app