version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
        - 7003:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks: 
      - redis_network

networks:
  redis_network:
    external: true
    name: net_app
    driver: overlay
    attachable: true